apiVersion: v1
kind: Service

metadata:
  name: food-admin
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: food-admin

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP