apiVersion: apps/v1
kind: Deployment

metadata:
  name: food-backend
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: food-backend

  template:
    metadata:
      labels:
        app: food-backend

    spec:
      serviceAccountName: food-backend-sa

      containers:
        - name: food-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000

          resources:
            requests:
              cpu: "100m"

          envFrom:
            - configMapRef:
                name: food-backend-config

            - secretRef:
                name: food-backend-secret

          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20